/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pl2_interfaz;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Window;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import pl2_java.Cliente;
import pl2_java.Evento;
import pl2_java.ManejarDatos;
import pl2_java.Reserva;

/**
 *
 * @author Alejandro
 */
public class AdminEvento_Panel extends javax.swing.JPanel {

    /**
     * Creates new form AdminEvento_Panel
     */
    private Evento evento;
    private int cont;
    private JFrame parentFrame;
    private ArrayList<Evento> eventos;
    
    public AdminEvento_Panel(Evento evento, JFrame frame) {
        this.evento = evento;
        this.parentFrame = frame;

        

        ManejarDatos.cargarEventos();
        eventos= ManejarDatos.getEventos();
        this.setPreferredSize(new Dimension(600, 400));
        this.setMaximumSize(new Dimension(Integer.MAX_VALUE, 326)); // evita que crezca verticalmente
        initComponents();
        
        jLabel1.setPreferredSize(new Dimension(200, 200)); // tamaño fijo: ancho = 200px, alto = 150px
        jLabel1.setText("");
        jTextArea2.addMouseWheelListener(e -> {
            java.awt.Component scroll = javax.swing.SwingUtilities.getAncestorOfClass(javax.swing.JScrollPane.class, this);
            if (scroll instanceof javax.swing.JScrollPane) {
                ((javax.swing.JScrollPane) scroll).dispatchEvent(e);
            }
        });
        
        jTextArea2.setEditable(false);               //Cargamos el texto
        jTextArea2.setLineWrap(true);
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setOpaque(false);
        jTextArea2.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jTextArea2.setText("Título: " + evento.getTitulo() +
                               "\nTipo: " + evento.getTipo() +
                               "\nDirección: " + evento.getDireccion() +
                               "\nFechas: " + evento.getFechas() +
                               "\nPrecio: " + evento.getPrecio() + "€" +
                               "\nCalificación: " + evento.getCalificacionMedia());
        
        ImageIcon img= evento.getImagen();          //Cargamos la imagen
        if (img != null) {
            int width = jLabel1.getPreferredSize().width;
            int height = jLabel1.getPreferredSize().height;
            Image imagen = img.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(imagen));
        } else {
            System.out.println("⚠️ Imagen es null al intentar ponerla en el panel.");
        }
    }
    
    
        

    
    
    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 472));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 150));

        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton1)
                        .addGap(99, 99, 99)
                        .addComponent(jButton2)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    Window window = SwingUtilities.getWindowAncestor(this);
    if (window instanceof JFrame) {
        window.dispose();   // Cerrar el JFrame que lo contiene
    }
    new Editar_Evento(evento).setVisible(true);  // Crear un JFrame para editar evento

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar este evento?",
                                                "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
         for(int i=0;i<eventos.size() ;i++){
             if(eventos.get(i).getTitulo().equals(evento.getTitulo())){
                 eventos.remove(i);
                 System.out.println(evento);
                 System.out.println(eventos);
                 break;
             }
         }
        
        ManejarDatos.setEventos(eventos);
        ManejarDatos.guardarEventos();  //Borramos el evento y guardamos los eventos.
        
        JOptionPane.showMessageDialog(this, "Evento eliminado exitosamente.");
        
        Window window = SwingUtilities.getWindowAncestor(this); 
    if (window instanceof JFrame) {
        window.dispose(); // Cerrar el Jframe que lo contiene
    }
        new Ver_Eventos().setVisible(true); //Recargar vista
    }
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
