/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pl2_interfaz;

import java.awt.Dimension;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JTextArea;
import pl2_java.Cliente;
import pl2_java.Evento;
import pl2_java.ManejarDatos;
import pl2_java.Reserva;


/**
 *
 * @author daniel
 */
public class Evento_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Evento_Panel
     */
    private Evento evento;
    private Cliente cliente;
    private ArrayList<Reserva> reservas;
    private String fechaSeleccionada;
    public Evento_Panel(Evento ev, Cliente cl) {
        this.evento = ev;
        this.cliente = cl;
        ManejarDatos.cargarReservas();
        reservas = ManejarDatos.getReservas();
        this.setPreferredSize(new Dimension(600, 400));
        this.setMaximumSize(new Dimension(Integer.MAX_VALUE, 120)); // evita que crezca verticalmente
        initComponents();
        for(Reserva r : reservas){
            if(r.getCliente().getCorreo_electronico().equals(cliente.getCorreo_electronico()) && r.getEvento().getTitulo().equals(evento.getTitulo())){
                jButton1.setText("RESERVADO");
                jButton1.setEnabled(false);
                break;
            }
        }
        jLabel1.setPreferredSize(new Dimension(200, 200)); // tamaño fijo: ancho = 200px, alto = 150px
        jLabel1.setText("");
        jTextArea2.addMouseWheelListener(e -> {
            java.awt.Component scroll = javax.swing.SwingUtilities.getAncestorOfClass(javax.swing.JScrollPane.class, this);
            if (scroll instanceof javax.swing.JScrollPane) {
                ((javax.swing.JScrollPane) scroll).dispatchEvent(e);
            }
        });
        for(String fecha : ev.getFechas()){
            jComboBox1.addItem(fecha);
        }
        this.fechaSeleccionada=(String) jComboBox1.getSelectedItem();
    }
    
    public void setTexto(String texto){
        jTextArea2.setText(texto);
        jTextArea2.setEditable(false);
        jTextArea2.setLineWrap(true);
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setOpaque(false);
        jTextArea2.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

    }
    public void setImagenEvento(ImageIcon img){
        if (img != null) {
            int width = jLabel1.getPreferredSize().width;
            int height = jLabel1.getPreferredSize().height;
            Image imagen = img.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(imagen));
        } else {
            System.out.println("⚠️ Imagen es null al intentar ponerla en el panel.");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 472));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 150));

        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton1.setText("RESERVAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println(evento);
        System.out.println(cliente);
        ManejarDatos.cargarReservas();
        reservas = ManejarDatos.getReservas();
        Reserva nueva = new Reserva(cliente, evento, fechaSeleccionada);
        reservas.add(nueva);
        ManejarDatos.guardarReservas();
        jButton1.setText("RESERVADO");
        jButton1.setEnabled(false);
        System.out.println(reservas);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
