/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pl2_interfaz;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import pl2_java.Cliente;
import pl2_java.ManejarDatos;

/**
 *
 * @author daniel
 */
public class Introducir_Contraseña_Nueva extends javax.swing.JFrame {

    /**
     * Creates new form Introducir_Contraseña_Nueva
     */
    private Cliente cliente;
    private int index;
    private ArrayList<Cliente> clientes;
    public Introducir_Contraseña_Nueva(Cliente c, int index) {
        this.cliente = c;
        this.index = index;
        initComponents();
        Image icono = Toolkit.getDefaultToolkit().getImage("Icono/IconoBien.png");
        setIconImage(icono);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaEvents");

        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Volver a Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("INTRODUCIR NUEVA CONTRASEÑA");

        jLabel1.setText("Introduce tu nueva contraseña");

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 65, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextField1))
                                .addGap(95, 95, 95))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(81, 81, 81))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(400, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ManejarDatos.cargarClientes();
        clientes = ManejarDatos.getClientes();
        String new_password = jFormattedTextField1.getText();
        boolean verdad = false;
        System.out.println(clientes);
        System.out.println(cliente);
        try{
            if (!new_password.equals(cliente.getClave())){
                System.out.println(new_password);
                clientes.remove(index);
                Cliente nuevo = new Cliente(cliente.getNombre(), cliente.getCorreo_electronico(), new_password, cliente.getTeléfono(), cliente.getDirección(), cliente.getTarjeta_de_credito(), cliente.isVIP());
                clientes.add(nuevo);
                ManejarDatos.guardarClientes();
                System.out.println(clientes);
                Login_User login = new Login_User();
                login.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Utiliza una contraseña diferente", "Contraseña ya utilizada", JOptionPane.ERROR_MESSAGE);
            }
                
            
        }catch(Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Introducir_Correo correo = new Introducir_Correo();
        correo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


// public static void main(String args[]) {
//     /* Set the Nimbus look and feel */
//     // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//      */
//     try {
//         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//             if ("Nimbus".equals(info.getName())) {
//                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                 break;
//             }
//         }
//     } catch (ClassNotFoundException ex) {
//         java.util.logging.Logger.getLogger(Introducir_Contraseña_Nueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//     } catch (InstantiationException ex) {
//         java.util.logging.Logger.getLogger(Introducir_Contraseña_Nueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//     } catch (IllegalAccessException ex) {
//         java.util.logging.Logger.getLogger(Introducir_Contraseña_Nueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//         java.util.logging.Logger.getLogger(Introducir_Contraseña_Nueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//     }
//     // </editor-fold>

//     /* Create and display the form */
//     java.awt.EventQueue.invokeLater(new Runnable() {
//         public void run() {
//             new Introducir_Contraseña_Nueva().setVisible(true);
//         }
//     });
// }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
