/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pl2_interfaz;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import pl2_java.Evento;
import pl2_java.ManejarDatos;

/**
 *
 * @author Alejandro
 */
public class Ver_Eventos extends javax.swing.JFrame {

    /**
     * Creates new form Ver_Eventos
     */

    public Ver_Eventos() {
        initComponents();
        cargarEventosEnPanel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollEventos = new javax.swing.JScrollPane();
        panelEventos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelEventos.setLayout(new javax.swing.BoxLayout(panelEventos, javax.swing.BoxLayout.Y_AXIS));
        scrollEventos.setViewportView(panelEventos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollEventos, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        new Gestionar_Eventos().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    private void cargarEventosEnPanel() {
    pl2_java.ManejarDatos.cargarEventos();
    java.util.ArrayList<pl2_java.Evento> eventos = pl2_java.ManejarDatos.getEventos();

    

    if (eventos == null || eventos.isEmpty()) {
        panelEventos.add(new javax.swing.JLabel("No hay eventos disponibles."));
    } else {
        for (Evento e : eventos) {
    // Panel contenedor para el evento:
    JPanel panelEvento = new JPanel();
    panelEvento.setLayout(new BorderLayout());
    panelEvento.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
    panelEvento.setMaximumSize(new Dimension(Integer.MAX_VALUE, 200)); // Altura fija

    // Imagen de portada:
    ImageIcon icono = e.getImagen();
    JLabel etiquetaImagen = new JLabel("");
    if (icono != null) {
        Image imagenEscalada = icono.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
         etiquetaImagen = new JLabel(new ImageIcon(imagenEscalada));
        etiquetaImagen.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelEvento.add(etiquetaImagen, BorderLayout.WEST);
    } else {
         etiquetaImagen = new JLabel("Sin imagen");
        etiquetaImagen.setPreferredSize(new Dimension(120, 120));
        etiquetaImagen.setHorizontalAlignment(JLabel.CENTER);
        etiquetaImagen.setVerticalAlignment(JLabel.CENTER);
        etiquetaImagen.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
        panelEvento.add(etiquetaImagen, BorderLayout.WEST);
}


    
    JTextArea texto = new JTextArea();
    texto.setText("Título: " + e.getTitulo() + "\nTipo: " + e.getTipo() + "\nDirección: " + e.getDireccion()+ "\nFechas: " + e.getFechas() + "\nPrecio: " + e.getPrecio() );
    texto.setEditable(false);
    texto.setLineWrap(true);
    texto.setWrapStyleWord(true);
    texto.setOpaque(false);
    texto.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

    JPanel panelBotones = new JPanel();
        //Botón editar
    JButton btnEditar = new JButton("Editar");
    btnEditar.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            // Falta hacer toda la logica...
            System.out.println("Editar: " + e.getTitulo());
            
        }
    });

    // Botón Eliminar
    JButton btnEliminar = new JButton("Eliminar");
    btnEliminar.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            //Falta hacer toda la logica...
            System.out.println("Eliminar: " + e.getTitulo());
            
        }
    });

    // Añadir botones al subpanel
    panelBotones.add(btnEditar);
    panelBotones.add(btnEliminar);
    
    
    panelEvento.add(etiquetaImagen, BorderLayout.WEST);
    panelEvento.add(texto, BorderLayout.CENTER);

    panelEvento.add(panelBotones, BorderLayout.SOUTH);
    
    panelEventos.add(panelEvento);
    panelEventos.add(Box.createRigidArea(new Dimension(0, 10))); // Separación entre eventos
}
    }

    
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ver_Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ver_Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ver_Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ver_Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ver_Eventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelEventos;
    private javax.swing.JScrollPane scrollEventos;
    // End of variables declaration//GEN-END:variables
}
